### ISSUE TITLE
Bad placing of verses with long lines

### ISSUE THREAD

**Issue by ppasedach** [paddymcall/SARIT-pdf-conversions#18]
pramanavarttikavrtti.pdf, p.2:
![auswahl_068](https://cloud.githubusercontent.com/assets/11517856/13427450/6210fb2a-dfb4-11e5-8661-d55f2b7fe851.png)
The last line of the verse extends into the margin.

**Comment by paddymcall** [comment]
This is a problem of hyphenation failing due to the lack of spaces around the comma. Should be fixed in xml first.

**Comment by ppasedach** [comment]
I doubt that the comma is the reason for hyphenation failing here, see the following:

```
\documentclass{article}
\usepackage{polyglossia}
\usepackage{fontspec}
\setdefaultlanguage{english}
\setotherlanguage{sanskrit}
\newfontfamily\devanagarifont[Script=Devanagari,Mapping=devanagarinumerals]{Chandas}
\begin{document}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX \textsanskrit{सूक्ताभ्यासविबर्द्धितव्यसनमित्यत्रानुबद्धस्पृहम् }

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\textsanskrit{,सूक्ताभ्यासविबर्द्धितव्यसनमित्यत्रानुबद्धस्पृहम् }

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX \textsanskrit{,सूक्ताभ्यासविबर्द्धितव्यसनमित्यत्रानुबद्धस्पृहम् }

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\textsanskrit{सूक्ताभ्यासविबर्द्धितव्यसनमित्यत्रानुबद्धस्पृहम् }
\end{document}
```

![auswahl_071](https://cloud.githubusercontent.com/assets/11517856/13819917/8399a466-eb9b-11e5-9910-94397b11c8b9.png)

Which makes me believe that again we're dealing with the 63 letter limit. Something I hope will be [overcome](http://tug.org/pipermail/xetex/2016-March/026543.html) relatively soon.

**Comment by ppasedach** [comment]
Well, well. Compiling the original example with the new xetex it still doesn't hyphenate, but inserting a space after the comma it does. And my sample file looks no different either, I still have to look a bit more into when hyphenation does and doesn't work.

**Comment by paddymcall** [comment]
Fixed in https://github.com/paddymcall/SARIT-corpus/commit/2517c81473342c945f2c0145970a49fa28fdfb30

see also issue #30
